[package]
name = "sequencer_engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "sequencer_engine"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
uuid = { workspace = true }
arc-swap = { workspace = true }
heapless = { workspace = true }
postcard = { workspace = true }
ableton-link-rs = "0.1.2"

[dev-dependencies]
postcard = { workspace = true }
proptest = { workspace = true }
