//! Golden postcard fixtures for the Swift↔Rust wire contract.
//!
//! `app/StepForgeTests/Fixtures/*.bin` are the byte-for-byte oracle for the
//! Swift codec (`PostcardTests.swift`, architecture-spec §11.2). They are
//! generated by the Rust engine, so this file holds the Rust-side source of
//! truth for what each fixture encodes.
//!
//! `event_fixtures()` / `command_fixtures()` feed two roles. `regen_all_fixtures`
//! (`#[ignore]`) rewrites every `.bin` when the Rust `Command` / `EngineEvent`
//! wire layout changes (e.g. a variant is inserted, shifting every later variant
//! tag). `event_fixtures_match_rust_encoding` / `command_fixtures_match_rust_encoding`
//! are non-ignored drift guards that run in every `cargo test` and fail the
//! moment a fixture's bytes diverge from the Rust encoder.
//!
//! The guards close the loop that bit PR #5: a variant insertion shifted event
//! tags and only the Swift tests caught it (and only when run). Regenerate after
//! an intentional wire change, from `engine/`:
//!
//!     cargo test -p sequencer_engine --test regen_fixtures -- --ignored

#![cfg(test)]

use sequencer_engine::command::Command;
use sequencer_engine::event::EngineEvent;
use sequencer_engine::models::VelocityZone;
use std::fs;
use std::path::PathBuf;

fn fixtures_dir() -> PathBuf {
    // core manifest = engine/crates/core → repo root is three `..`.
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../app/StepForgeTests/Fixtures")
}

/// The canonical `EngineEvent` value each `ev_*.bin` fixture encodes. Kept in
/// Rust declaration order only for readability — postcard tags by declaration
/// index, so reordering here reorders the tags (and the regen tool rewrites the
/// bytes accordingly).
fn event_fixtures() -> Vec<(&'static str, EngineEvent)> {
    vec![
        ("ev_bpm_123", EngineEvent::BpmChanged { bpm: 123.0 }),
        (
            "ev_playhead_2_7",
            EngineEvent::Playhead {
                track_idx: 2,
                step_idx: 7,
            },
        ),
        (
            "ev_playstate_true",
            EngineEvent::PlayStateChanged { playing: true },
        ),
        ("ev_overflow_7", EngineEvent::Overflow { dropped: 7 }),
        (
            "ev_undoavail_1_true",
            EngineEvent::UndoAvailable {
                track_idx: 1,
                available: true,
            },
        ),
        (
            "ev_error_m7_boom",
            EngineEvent::Error {
                code: -7,
                message: "boom".to_string(),
            },
        ),
        (
            "ev_linkenabled_true",
            EngineEvent::LinkEnabledChanged { enabled: true },
        ),
    ]
}

/// The canonical `Command` value each `cmd_*.bin` fixture encodes. Values mirror
/// the assertions in `PostcardTests.swift` (the Swift oracle) so both sides of
/// the wire contract are pinned from Rust.
fn command_fixtures() -> Vec<(&'static str, Command)> {
    vec![
        ("cmd_play", Command::Play),
        ("cmd_stop", Command::Stop),
        ("cmd_addtrack", Command::AddTrack),
        ("cmd_setbpm_140", Command::SetBpm { bpm: 140.0 }),
        (
            "cmd_setstep_0_3_accent",
            Command::SetStep {
                track_idx: 0,
                step_idx: 3,
                zone: VelocityZone::Accent,
            },
        ),
        (
            "cmd_setmuted_2_true",
            Command::SetTrackMuted {
                track_idx: 2,
                muted: true,
            },
        ),
        (
            "cmd_setmidich_10",
            Command::SetGlobalMidiChannel { channel: 10 },
        ),
        (
            "cmd_setmididest_1_2_300",
            Command::SetMidiDestinations {
                endpoints: vec![1u32, 2, 300],
            },
        ),
        (
            "cmd_loadsession_9_9",
            Command::LoadSession {
                bytes: vec![9u8, 9],
            },
        ),
    ]
}

#[test]
#[ignore = "fixture-regeneration tool — run explicitly with --ignored"]
fn regen_all_fixtures() {
    let dir = fixtures_dir();
    assert!(dir.exists(), "fixtures dir not found at {}", dir.display());

    for (name, ev) in event_fixtures() {
        let bytes = postcard::to_allocvec(&ev).expect("serialize event");
        fs::write(dir.join(format!("{name}.bin")), bytes)
            .unwrap_or_else(|e| panic!("write {name}.bin: {e}"));
    }
    for (name, cmd) in command_fixtures() {
        let bytes = postcard::to_allocvec(&cmd).expect("serialize command");
        fs::write(dir.join(format!("{name}.bin")), bytes)
            .unwrap_or_else(|e| panic!("write {name}.bin: {e}"));
    }
}

#[test]
fn event_fixtures_match_rust_encoding() {
    let dir = fixtures_dir();
    for (name, ev) in event_fixtures() {
        let expected = postcard::to_allocvec(&ev).expect("serialize event");
        let fixture = fs::read(dir.join(format!("{name}.bin")))
            .unwrap_or_else(|e| panic!("read {name}.bin: {e}"));
        assert_eq!(
            expected, fixture,
            "{name}.bin no longer matches the Rust `EngineEvent` encoding. Run \
             `cargo test -p sequencer_engine --test regen_fixtures -- --ignored` \
             to refresh, then commit the new bytes (only if the wire layout \
             change was intended).",
        );
    }
}

#[test]
fn command_fixtures_match_rust_encoding() {
    let dir = fixtures_dir();
    for (name, cmd) in command_fixtures() {
        let expected = postcard::to_allocvec(&cmd).expect("serialize command");
        let fixture = fs::read(dir.join(format!("{name}.bin")))
            .unwrap_or_else(|e| panic!("read {name}.bin: {e}"));
        assert_eq!(
            expected, fixture,
            "{name}.bin no longer matches the Rust `Command` encoding. Run \
             `cargo test -p sequencer_engine --test regen_fixtures -- --ignored` \
             to refresh, then commit the new bytes (only if the wire layout \
             change was intended).",
        );
    }
}
