[workspace]
resolver = "2"
members = ["crates/core", "crates/ffi"]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
sequencer_engine = { path = "crates/core" }
serde = { version = "1", features = ["derive"] }
postcard = { version = "1", features = ["alloc"] }
uuid = { version = "1", features = ["serde", "v4"] }
arc-swap = "1"
heapless = "0.8"
proptest = "1"
