#ifndef SEQUENCER_ENGINE_H
#define SEQUENCER_ENGINE_H

#pragma once

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Maximum bytes an event may occupy on the hot (fixed-slot) RT channel. Events
 * that would exceed this (e.g. `Serialized`) are routed to the separate off-RT
 * large-event channel (design decision D5; amendment A2).
 */
#define MAX_EVENT_BYTES 128

/**
 * Status returned by every `extern "C"` entry point (CLAUDE.md Hard Rule 3).
 * Discriminants are stable across releases — do not renumber existing variants.
 */
typedef enum EngineResult {
    /**
     * Success.
     */
    Ok = 0,
    /**
     * A command/event byte buffer could not be decoded (non-fatal).
     */
    ErrDecode = 1,
    /**
     * A NULL or invalid handle was supplied.
     */
    ErrInvalidHandle = 2,
    /**
     * A buffer pointer/length was invalid.
     */
    ErrInvalidBuffer = 3,
    /**
     * Any other failure; details via an `EngineEvent::Error`.
     */
    ErrOther = 4,
} EngineResult;

/**
 * Opaque handle exchanged across the FFI. Never dereferenced in Swift.
 */
typedef struct EngineHandle {
    uint8_t _private[0];
} EngineHandle;

/**
 * Create a new engine. Returns an opaque handle (never NULL).
 */
struct EngineHandle *engine_new(void);

/**
 * Free an engine. NULL is a tolerated no-op. `engine_stop` must have returned first.
 *
 * # Safety
 * `engine` is NULL or a handle from [`engine_new`]; no concurrent `engine_*` call.
 */
void engine_free(struct EngineHandle *engine);

/**
 * Start playback. Stub: no-op, returns Ok. The engine plan implements.
 */
enum EngineResult engine_start(struct EngineHandle *engine);

/**
 * Stop playback. Stub: no-op. Must be called and return before `engine_free`.
 */
enum EngineResult engine_stop(struct EngineHandle *engine);

/**
 * Submit a command as postcard bytes. Returns `ErrDecode` on malformed bytes
 * (non-fatal).
 *
 * Apply path (Task 18+): the decoded command is applied SYNCHRONOUSLY on the
 * caller thread until Task 20 wires the real lock-free MPSC queue + state
 * worker (`engine_start`). This lets `LoadSession` / `SetBpm` / etc. round-trip
 * through the C ABI in integration tests today; the queue/worker swap is
 * mechanical and confined to this body + `engine_start`.
 *
 * # Safety
 * `cmd_ptr` is valid for `cmd_len` bytes for the duration of the call (or NULL
 * when `cmd_len == 0`); `engine` is a valid handle.
 */
enum EngineResult engine_submit_command(struct EngineHandle *engine,
                                        const uint8_t *cmd_ptr,
                                        uintptr_t cmd_len);

/**
 * Drain at most one event into `*out_ptr`/`*out_len`. An empty/zero-length
 * result means the queue is drained (design decision D5 / amendment A13).
 * Stub: always drained (no events produced yet). Buffers must be freed via
 * [`engine_free_bytes`].
 *
 * # Safety
 * `out_ptr`/`out_len` are valid writable pointers (or NULL); `engine` is valid.
 */
enum EngineResult engine_drain_events(struct EngineHandle *engine,
                                      uint8_t **out_ptr,
                                      uintptr_t *out_len);

/**
 * Serialize the current session into `*out_ptr`/`*out_len` as a versioned
 * postcard `SessionEnvelope`. The buffer is Rust-allocated and must be freed
 * with [`engine_free_bytes`] (Hard Rule 4).
 *
 * NULL contract asymmetry: unlike [`engine_drain_events`] — a pull that
 * tolerates NULL out-params and no-ops when empty — this MUST receive non-NULL
 * `out_ptr`/`out_len`, since it has to hand back both the buffer pointer and
 * its length for the caller to read and later free (NULL → `ErrInvalidBuffer`).
 *
 * # Safety
 * `out_ptr`/`out_len` are valid writable, non-NULL pointers; `engine` is valid.
 */
enum EngineResult engine_serialize(struct EngineHandle *engine,
                                   uint8_t **out_ptr,
                                   uintptr_t *out_len);

/**
 * Free a buffer returned by `engine_drain_events` / `engine_serialize`.
 * `engine_free_bytes(NULL, 0)` is a no-op (Hard Rule 4).
 *
 * # Safety
 * `ptr`/`len` are NULL/0 or exactly a pair returned by this crate.
 */
void engine_free_bytes(uint8_t *ptr, uintptr_t len);

#endif  /* SEQUENCER_ENGINE_H */
