import XCTest
@testable import StepForge

/// Postcard codec conformance tests. Every golden byte array is loaded from
/// `Fixtures/*.bin`, which were **generated by the Rust engine** (`postcard::
/// to_allocvec`) — zero hand-transcription. These are the byte-for-byte oracle for
/// the Swift codec (architecture-spec §11.2). If the engine's wire layout changes,
/// regenerate the fixtures (see the plan's wire-format step) and these still hold.
///
/// Run: `xcodebuild test -scheme StepForge -sdk iphonesimulator`.
final class PostcardTests: XCTestCase {

    private func load(_ name: String) -> [UInt8] {
        guard let url = Bundle(for: PostcardTests.self).url(forResource: name, withExtension: "bin") else {
            XCTFail("missing fixture \(name).bin"); return []
        }
        return [UInt8](try! Data(contentsOf: url))
    }

    // MARK: - Command encode → engine bytes

    func testCommandUnitVariants() {
        XCTAssertEqual(Command.play.encode(), load("cmd_play"))
        XCTAssertEqual(Command.stop.encode(), load("cmd_stop"))
        XCTAssertEqual(Command.addTrack.encode(), load("cmd_addtrack"))
    }

    func testCommandSetBpm() {
        XCTAssertEqual(Command.setBpm(bpm: 140.0).encode(), load("cmd_setbpm_140"))
    }

    func testCommandSetStep() {
        XCTAssertEqual(Command.setStep(trackIdx: 0, stepIdx: 3, zone: .accent).encode(),
                       load("cmd_setstep_0_3_accent"))
    }

    func testCommandSetTrackMuted() {
        XCTAssertEqual(Command.setTrackMuted(trackIdx: 2, muted: true).encode(), load("cmd_setmuted_2_true"))
    }

    func testCommandSetGlobalMidiChannel() {
        XCTAssertEqual(Command.setGlobalMidiChannel(channel: 10).encode(), load("cmd_setmidich_10"))
    }

    func testCommandSetMidiDestinations() {
        XCTAssertEqual(Command.setMidiDestinations(endpoints: [1, 2, 300]).encode(),
                       load("cmd_setmididest_1_2_300"))
    }

    func testCommandLoadSession() {
        XCTAssertEqual(Command.loadSession(bytes: [9, 9]).encode(), load("cmd_loadsession_9_9"))
    }

    // Whole-pattern clipboard (CLAP parity — issue #33).
    func testCommandPatternClipboard() {
        XCTAssertEqual(Command.copyPattern(index: 2).encode(),   load("cmd_copypattern_2"))
        XCTAssertEqual(Command.cutPattern(index: 3).encode(),    load("cmd_cutpattern_3"))
        XCTAssertEqual(Command.pastePattern(index: 4).encode(),  load("cmd_pastepattern_4"))
        XCTAssertEqual(Command.clearPattern(index: 5).encode(),  load("cmd_clearpattern_5"))
    }

    // Pattern-level undo (issue #34).
    func testCommandUndoPattern() {
        XCTAssertEqual(Command.undoPattern(index: 6).encode(), load("cmd_undopattern_6"))
    }

    func testCommandSetLinkEnabled() {
        XCTAssertEqual(Command.setLinkEnabled(enabled: true).tag, 33)
    }

    // MARK: - Engine bytes → Event decode

    func testEventPlayhead() {
        XCTAssertEqual(EngineEvent.decode(load("ev_playhead_2_7")), .playhead(trackIdx: 2, stepIdx: 7))
    }
    func testEventPlayStateChanged() {
        XCTAssertEqual(EngineEvent.decode(load("ev_playstate_true")), .playStateChanged(playing: true))
    }
    func testEventBpmChanged() {
        XCTAssertEqual(EngineEvent.decode(load("ev_bpm_123")), .bpmChanged(bpm: 123.0))
    }
    func testEventOverflow() {
        XCTAssertEqual(EngineEvent.decode(load("ev_overflow_7")), .overflow(dropped: 7))
    }
    func testEventUndoAvailable() {
        XCTAssertEqual(EngineEvent.decode(load("ev_undoavail_1_true")), .undoAvailable(trackIdx: 1, available: true))
    }
    func testEventError() {
        XCTAssertEqual(EngineEvent.decode(load("ev_error_m7_boom")), .error(code: -7, message: "boom"))
    }
    func testEventLinkEnabledChanged() {
        XCTAssertEqual(EngineEvent.decode(load("ev_linkenabled_true")), .linkEnabledChanged(enabled: true))
    }

    // MARK: - Model decode

    func testUuidNilDecode() {
        var r = PostcardReader(load("uuid_nil"))
        XCTAssertEqual(r.readUUID(), UUID(uuid: (0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)))
    }

    func testStepDecode() {
        var a = PostcardReader(load("step_inactive"))
        XCTAssertEqual(Step(from: &a), Step(active: false, velocityZone: .mid, microTimingOffset: 0, ratchet: .off))
        var b = PostcardReader(load("step_accent"))
        XCTAssertEqual(Step(from: &b), Step(active: true, velocityZone: .accent, microTimingOffset: 0, ratchet: .off))
        var c = PostcardReader(load("step_low_ratchet_x2"))
        XCTAssertEqual(Step(from: &c), Step(active: true, velocityZone: .low, microTimingOffset: 0, ratchet: .x2))
    }

    func testSessionDefaultDecode() {
        var r = PostcardReader(load("session_default"))
        let env = SessionEnvelope(from: &r)
        XCTAssertEqual(env?.version, 1)
        XCTAssertEqual(env?.session.bpm, 120.0)
        XCTAssertEqual(env?.session.syncSource, .free)
        XCTAssertEqual(env?.session.globalMidiChannel, 10)
        XCTAssertEqual(env?.session.activePatternIndex, 0)
        XCTAssertEqual(env?.session.midiDestinations, [])
        XCTAssertEqual(env?.session.patterns.count, 9)
        XCTAssertTrue(env?.session.patterns.allSatisfy { $0 == nil } ?? false)
    }

    func testSessionOneHitDecode() {
        // bpm 150; patterns[0] = default Pattern (nil Uuids, 4 tracks); track[0]
        // step[0] = active Accent, rest inactive Mid.
        var r = PostcardReader(load("session_one_hit"))
        let env = SessionEnvelope(from: &r)
        XCTAssertEqual(env?.version, 1)
        XCTAssertEqual(env?.session.bpm, 150.0)

        let pattern = env?.session.patterns[0]
        XCTAssertNotNil(pattern)
        XCTAssertEqual(pattern?.tracks.count, 4)
        XCTAssertEqual(pattern?.tracks[0].midiNote, 36)
        XCTAssertEqual(pattern?.tracks[0].length, 16)
        XCTAssertEqual(pattern?.tracks[0].speedRatio, 1.0)
        let hit = pattern?.tracks[0].steps[0]
        XCTAssertEqual(hit?.active, true)
        XCTAssertEqual(hit?.velocityZone, .accent)
        XCTAssertEqual(pattern?.tracks[0].steps[1].active, false)
        XCTAssertEqual(pattern?.tracks[0].steps[15].active, false)

        // Default tracks use the nil UUID.
        let nilUUID = UUID(uuid: (0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))
        XCTAssertEqual(pattern?.tracks[0].id, nilUUID)
        // Follow action default: after_loops 1, None.
        XCTAssertEqual(pattern?.followAction.afterLoops, 1)
        XCTAssertEqual(pattern?.followAction.action, FollowActionType.none)
    }

    // MARK: - Variant index sanity (postcard index = Rust declaration order)

    func testCommandVariantOrder() {
        XCTAssertEqual(Command.setStep(trackIdx: 0, stepIdx: 0, zone: .mid).tag, 0)
        XCTAssertEqual(Command.addTrack.tag, 8)
        XCTAssertEqual(Command.play.tag, 28)
        XCTAssertEqual(Command.stop.tag, 29)
        XCTAssertEqual(Command.midiClockTick.tag, 34)
        XCTAssertEqual(Command.copyPattern(index: 0).tag,  35)
        XCTAssertEqual(Command.cutPattern(index: 0).tag,   36)
        XCTAssertEqual(Command.pastePattern(index: 0).tag, 37)
        XCTAssertEqual(Command.clearPattern(index: 0).tag, 38)
        XCTAssertEqual(Command.undoPattern(index: 0).tag, 39)
    }

    // MARK: - Robustness (Hard Rule 3: never panic across FFI)

    func testMalformedEventReturnsNil() {
        XCTAssertNil(EngineEvent.decode([0xff, 0xff, 0xff, 0xff]))   // unknown variant + junk
    }
    func testTruncatedEventReturnsNil() {
        XCTAssertNil(EngineEvent.decode([0x09]))                       // playhead tag, no payload
    }
    func testUnknownEventVariantReturnsNil() {
        XCTAssertNil(EngineEvent.decode([0x63]))                       // variant 99 — future-proof skip
    }
    func testTruncatedVarintReturnsNil() {
        XCTAssertNil(EngineEvent.decode([0x80]))                       // unterminated varint
    }
}
